Lecture eval
DevKor-github/ku-key_front pull request #10
Opened 2024-08-09 10:29 UTC by halionaz

허허.. 다음 PR 갑니다잇

## 강의평가 페이지
- 강의평가 페이지는 시간표에 등록된 강의를 눌러 들어갈 수도, 강의 검색을 통해 들어갈 수도 있습니다
- 첫 화면에서는 강의 전체에 대한 평가가 요약되어 보여집니다. 
- 세부 리뷰 페이지에 대해서는 강의 열람권을 구매해야 들어갈 수 있습니다. (현재 열람권 구매 로직이 없어서 백엔드분들께 요청해야 할 것 같습니다)
- Write your Review 페이지를 통해 강의평을 등록할 수 있습니다

2024-08-15 01:06 UTC, Virtuso1225 requested changes
코드 잘 봤습니다~ 고생하셨습니다!!
몇 가지 코멘트 달아뒀습니다!
PREV 버튼 관련해서 한 가지 수정하면 좋을 것 같은 사항이 있습니다 ❗️

2024-08-15 01:06 UTC, Virtuso1225 commented on src/pages/CourseReviewPage/index.tsx
> +        <button className={cx(FriendPageBtnStyle({ prev: true }), css({ flexShrink: 0 }))} onClick={() => navigate(-1)}>
QA 있습니다~
1. 강의평 보는 페이지에서 write your review 눌러 강의평 작성 페이지에서 강의평 작성.
2. 강의평 작성 완료시 강의평 보는 페이지로 이동.
3. 해당 페이지에서 PREV 버튼 클릭시 `navigate(-1)`로 인해 다시 강의평 작성 페이지로 이동

2024-08-15 01:06 UTC, Virtuso1225 commented on src/pages/CourseReviewPage/index.tsx
> +        <button className={cx(FriendPageBtnStyle({ prev: true }), css({ flexShrink: 0 }))} onClick={() => navigate(-1)}>
이전 페이지면 타임테이블 로 가는 게 옳지 않을까? 라는 생각이 들었습니다..!

2024-08-15 01:06 UTC, Virtuso1225 commented on src/components/courseReview/ReviewHeader.tsx
> +        to={`/course-review/write/${courseCode}/${prof}`}
이미 작성한 강의평이 있는 경우 사전에 해당 링크 눌렀을 때 "이미 강의평을 작성한 강의입니다" 등의 안내가 나가고 라우팅이 없어야할 것 같습니다..!

2024-08-15 01:06 UTC, Virtuso1225 commented on src/components/courseReview/ReviewText.tsx
> +      <textarea
Textarea 리사이징 가능한 표시인 우측 하단 귀퉁이 없애는 게 좀 더 예쁘지 않을까? 라는 생각이

2024-08-15 01:06 UTC, Virtuso1225 commented on src/components/courseReview/ReviewTotalRate.tsx
> +    radioArray.push(
radioArray 라서 뭔가 radio tag 같은 input을 생각했는데 아니었군요..!? 다른 이름이 좀 더 어울릴듯 한데 어떤가요.?

2024-08-15 01:06 UTC, Virtuso1225 commented on src/components/courseReview/TotalRate.tsx
> +          Course Review <ChevronRight size={18} />
강의 열람권 없으면 해당 링크 클릭시 안내하고 라우팅 하지 않기?

2024-08-15 01:06 UTC, Virtuso1225 commented on src/components/timetable/Button/ShareBtn.tsx
>      <button className={BtnStyle} onClick={shareHandler}>
이거 해보니까 화면 사이즈에 따라 저장되는 이미지 사이즈가 달라지는 거 같은데, 딱 정해진 예쁜 사이즈대로 나오는 게 좋지 않을까? 라는 생각이 들었는데, 또 뷰에 맞춰서 다운 되는 것도 좋은건가? 싶기도 하고...
한가지 들었던 생각은,,이거 생각보다 이미지 다운이 오래 걸리네요.? 속도 빠르게 할 방법이 없을까요?

2024-08-15 07:11 UTC, halionaz commented on src/pages/CourseReviewPage/index.tsx
> +        <button className={cx(FriendPageBtnStyle({ prev: true }), css({ flexShrink: 0 }))} onClick={() => navigate(-1)}>
오 맞는 것 같습니다! 수정해둘게요

2024-08-16 06:31 UTC, halionaz commented on src/components/courseReview/TotalRate.tsx
> +          Course Review <ChevronRight size={18} />
강의 열람권 소유 여부에 대한 엔드포인트가 따로 없어서 일단 페이지 들어가서
GET 요청을 날린 후, 에러가 나면 navigate(-1) 해주고 있는데 어색할까요?

2024-08-16 06:33 UTC, halionaz commented on src/components/timetable/Button/ShareBtn.tsx
>      <button className={BtnStyle} onClick={shareHandler}>
흐으으음 그러게요
원래 강의만 얹혀져있을 때는 이정도로 느리진 않았는데
확실히 속도 이슈가 있군요...

2024-08-16 07:10 UTC, halionaz commented
> 이미 작성한 강의평이 있는 경우 사전에 해당 링크 눌렀을 때 "이미 강의평을 작성한 강의입니다" 등의 안내가 나가고 라우팅이 없어야할 것 같습니다..!

요거 시흔이햄한테 엔드포인트 요청해놔서 서버에 반영되는 대로 추가할 예정이고
나머지는 모두 코드 수정 / 코멘트 남겨놨습니다~
한번 확인 부탁드랴용

2024-08-17 01:47 UTC, Virtuso1225 approved these changes
LET'S GO

2024-08-17 01:55 UTC, merged