Community page/post edit button
DevKor-github/ku-key_front pull request #12
Opened 2024-08-17 01:55 UTC by Virtuso1225

커뮤니티에 필요한 기능들 최우선적으로 넣어뒀습니다~
한 번씩 다 QA 필요할 것 같습니다!
1. 게시글 수정
2. 게시글 신고
3. 게시글 삭제
4. 링크 복사
 
 위의 4개 기능들을 구현 했습니다!
 - 게시글 수정할 때 아직 새로고침 핸들링 혹은 Persistent 처리를 해두지 않아서, 해당 처리는 추가해야합니당
 - 각 신고, 삭제 등은 기능은 잘 작동하나, ux 측면에서, 부가적인 설명이나, 안내창이 더 떠야하는 점들은 추가해야할 것 같습니다..

2024-08-20 07:26 UTC, halionaz requested changes
확실히 modal 같은 친구들을 훅으로 관리하니까 코드가 깔끔하고 좋네요
현재 코드 로직 상 고쳐야 할 부분은 많진 않고 코멘트로 남겨뒀습니다~

찾은 버그 몇가지 레포트 드리자면

이미 신고 했을 경우, 다시 신고했을 때의 에러 핸들링이 alert 창으로라도 들어가면 좋을 것 같고,
수정을 하다가 그냥 나온 후, Create Post를 하면 persistedPostData 때문에 그 전 데이터가 form에 남는 버그가 있읍니다

아 그리고 타입에러가 꽤나 있어서 버셀 에러가 나는데
버셀 에러 해결해주시면 감사하겠습니다

수고 많으셨소 🔥

2024-08-20 07:26 UTC, halionaz commented on src/api/hooks/community.ts
> +    queryFn: ({ pageParam: cursor }) => getHotPosts(10, cursor.toString()),
오 여기선 cursorId를 string으로 주는구나

2024-08-20 07:26 UTC, halionaz commented on src/util/create-file-from -url.ts
이거 파일명이 살짝 요상한데 의도하신 부분일까요

2024-08-20 07:26 UTC, halionaz commented on src/components/timetable/Dropdown.tsx
> +      <DropdownMenu.Trigger asChild disabled={disabled}>
뭐야 요런 옵션이 있었네 👍

2024-08-20 07:26 UTC, halionaz commented on src/components/community/HotBoard/HotBoard.tsx
요 친구 index.ts로 바꿔서 디렉토리 주소 중복 막는거 어떤가요?!

2024-08-20 07:26 UTC, halionaz commented on src/api/hooks/community.ts
>    })
initialData가 따로 없어서 HotBoardHorizontalPreview에서 타입에러가 발생하고 있습니다!

2024-08-20 07:26 UTC, halionaz commented on src/components/community/HotBoard/HotBoard.tsx
> +          <div key={post.id} ref={fetchNextRef}>
헉 근데 이거 map으로 매번 fetchNextRef 덮어씌워서 마지막 div 요소에 ref 부여해주는 로직인가요?

2024-08-20 07:26 UTC, halionaz commented on src/components/community/HotBoard/HotBoard.tsx
> +          <div key={post.id} ref={fetchNextRef}>
map으로 감싸진 코드블럭 마지막에 ref div를 주는게 직관적일 거 같아서 수정하면 좋을듯 한데
이것도 잘 작동하네요

2024-08-20 07:26 UTC, halionaz commented on src/components/community/HotBoard/HotBoardHorizontalPreview.tsx
> +  const secondColumn = hotPosts.data.slice(3, 6)
hook 쪽 코멘트에 남기긴 했지만 그쪽에서 initial Data 설정해주거나 여기서 에러핸들링 해주는 것이 좋을듯!!

2024-08-20 07:26 UTC, halionaz commented on src/components/community/post/PostWriteSection.tsx
> +  const [initialData, setInitialData] = useAtom(persistedPostData)
요거 type이 edit일때만 적용하는걸로 로직 바꿔야 할 거 같아요 
지금은 write일 때도 persistedPostData 있으면 불러오는 버그가 있어서
write로 들어오면 persistedAtom을 날리거나, 아니면 form에 불러오는걸 방지해야 할 듯합니다

2024-08-20 09:39 UTC, Virtuso1225 commented on src/util/create-file-from -url.ts
뭐야 뒤에 왜 띄어쓰기가 더 있지..수정해야겠따

2024-08-20 09:39 UTC, Virtuso1225 commented on src/components/community/HotBoard/HotBoard.tsx
음 좋은 의견입니당

2024-08-20 09:40 UTC, Virtuso1225 commented on src/api/hooks/community.ts
>    })
아 해당 부분 디자인이 애매해서 작업하다가 보류 했습니당

2024-08-20 09:41 UTC, Virtuso1225 commented on src/components/community/HotBoard/HotBoard.tsx
> +          <div key={post.id} ref={fetchNextRef}>
근데 그게 어떤 차이인가요?

2024-08-20 12:07 UTC, Virtuso1225 commented on src/components/community/post/PostWriteSection.tsx
> +  const [initialData, setInitialData] = useAtom(persistedPostData)
근데 이게 edit 버튼을 통해서 들어온 경우에만 안에 내용이 있는거라 edit으로 들어왔다가 컴포넌트 언마운트 될 때 초기화해줘서 다시 들어왔을 때 비어있게 하는 건 어떤지

2024-08-20 12:14 UTC, halionaz commented on src/components/community/post/PostWriteSection.tsx
> +  const [initialData, setInitialData] = useAtom(persistedPostData)
굿굿 좋습니다

2024-08-21 03:02 UTC, halionaz approved these changes
이륙! 🛫

2024-08-21 03:03 UTC, merged