feat: error 핸들링 한글 삭제
DevKor-github/ku-key_front pull request #138
Opened 2024-12-01 07:04 UTC by Virtuso1225

## 📌 내용

- 친구 검색 ux 수정 및 useSuspense로 교체
- queryParam으로 검색 관리를 할 수 있어 data fetching 자체도 searchResult 내부에 넣어뒀어요.
- 로그인 파트에서 한글로 에러 메세지 분기를 쳐서 띄어주고 있었는데, 한글을 영어로 교체했어요
## ☑️ 체크 사항

- [ ]

## ❗ Related Issues

2024-12-01 13:04 UTC, halionaz requested changes

2024-12-01 13:04 UTC, halionaz commented on src/components/timetable/Friend/FriendsManage.tsx
> +    [setQueryParam],
훨씬 깔끔하네요 굿굿굿

2024-12-01 13:04 UTC, halionaz commented on src/components/ui/spinner/inde.tsx
`index.tsx` 오타가 난 것 같아요

로딩 스피너는 로컬 Suspense의 중간에 박히는 스피너 컴포넌트 하나이고
로딩 스크린은 화면 전역을 차지하여(100vh) 스피너를 보여주는 화면으로 구분하신거죠?

2024-12-01 23:43 UTC, Virtuso1225 commented on src/components/ui/spinner/inde.tsx
맞어용

2024-12-02 03:27 UTC, halionaz approved these changes

2024-12-02 03:50 UTC, merged