Feat/lang dropdown
DevKor-github/ku-key_front pull request #27
Opened 2024-09-03 12:46 UTC by halionaz

얘도 우선 기능 구현 먼저 머지하겠습니다~
디자인은 현아씨한테 좀 다듬어달라 요청했습니다

- 드롭다운을 통해 언어를 편하게 등록하고 (멀티 value를 받을 수 있음), 삭제할 수 있읍니다

2024-09-07 10:34 UTC, Virtuso1225 commented on src/components/mypage/UserInfo.tsx
<img width="462" alt="스크린샷 2024-09-07 오후 7 24 43" src="https://github.com/user-attachments/assets/3b7c86ca-4426-40f9-94e5-288d0bea5f3e">
이거 여전히 색상이 안 보이는데, 한 번 확인 해보셔야할 것 같아유

2024-09-07 10:34 UTC, Virtuso1225 commented on src/components/ui/dropdown/LanguageDropdown.tsx
<img width="945" alt="스크린샷 2024-09-07 오후 7 32 58" src="https://github.com/user-attachments/assets/a87cd15b-c7b7-46f0-9540-102b578d5a68">

이렇게 언어가 많아지는 경우의 UI에서 수정이 필요해 보입니다!

2024-09-11 06:47 UTC, halionaz commented on src/components/mypage/UserInfo.tsx
이거 pandaCSS 레시피 문제인거 같은데 아마 빌드되면 잘 보일 거 같습니다
🐼 판다 거 참 요상하네

2024-09-11 16:03 UTC, Virtuso1225 requested changes
음 좋아요 언어 선택도 아예 5개로 핸들링한 거 좋습니다

2024-09-11 16:03 UTC, Virtuso1225 commented on src/components/mypage/Contents/PublicProfile.tsx
Nation이 선택된 상태에서
<img width="500" alt="스크린샷 2024-09-12 오전 1 02 28" src="https://github.com/user-attachments/assets/1c747167-1998-4230-b760-4e22f73c0128">
국가 선택이 default가 있으면 default로 보여져야할 것 같아요

2024-09-11 16:08 UTC, halionaz commented on src/components/mypage/Contents/PublicProfile.tsx
어? 이거 처리되어있는데 왜 안보이지

2024-09-12 01:53 UTC, merged