Design/my page
DevKor-github/ku-key_front pull request #36
Opened 2024-09-05 10:10 UTC by halionaz

변경된 포인트샵 레이아웃 적용하고, KU-key의 화폐 Sugar 사진 적용했습니다~

아마 마이페이지는 디자인이 더 변경될 여지가 있어서 요건 확정은 아니고 디자인 맞추어 추가 PR 올리겠습니다
그리고 캐릭터를 해금한 내에서 선택할 수 있는 걸로 백 API가 변경될 예정이라, 요거 맞춰서 쿠키 캐릭터 사진들 다 맞추어 넣을게용

2024-09-07 17:06 UTC, Virtuso1225 requested changes
svg는 다시 한 번 고려를 해봐야할 것 같아요..!

2024-09-07 17:06 UTC, Virtuso1225 commented on src/components/mypage/Contents/PointHistory.tsx
<img width="1244" alt="스크린샷 2024-09-08 오전 1 45 04" src="https://github.com/user-attachments/assets/231ec235-a1d4-4fed-9e4b-2278be2ecd28">
방금 출석체크하면서 포인트 확인을 했는데, 출석체크하면서 사용자의 point query key에 대한 Invalidation도 있어야할 것 같아요

2024-09-07 17:06 UTC, Virtuso1225 commented on src/components/mypage/Contents/PointShop/PointStatus.tsx
기존에 있던 안내가 사라졌군요

2024-09-07 17:06 UTC, Virtuso1225 commented on src/index.css
이거는 어디에 사용되는 폰트인가요

2024-09-07 17:06 UTC, Virtuso1225 commented on src/components/mypage/Contents/PointShop/Showcase.tsx
> +              alert('Somthing is Wrong!')
포인트 부족한 경우에도 잘 처리되는 거 확인했습니다~

2024-09-07 17:06 UTC, Virtuso1225 commented on src/components/mypage/Contents/PointShop/Showcase.tsx
> +            ))}
이거는 그냥 6개 요소를 가진 배열을 만들기 위함인가요?

2024-09-08 08:59 UTC, halionaz commented on src/index.css
포인트샵 입니다~

2024-09-08 08:59 UTC, halionaz commented on src/components/mypage/Contents/PointShop/Showcase.tsx
> +            ))}
넵 그냥 1~6레벨 부여용

2024-09-08 08:59 UTC, halionaz commented on src/components/mypage/Contents/PointShop/PointStatus.tsx
포인트 내역으로 옮겨졌어요

2024-09-08 08:59 UTC, halionaz commented on src/components/mypage/Contents/PointHistory.tsx
최고

2024-09-09 00:24 UTC, Virtuso1225 approved these changes
가시죠!

2024-09-09 01:33 UTC, merged