/timetable
DevKor-github/ku-key_front pull request #7
Opened 2024-07-03 10:11 UTC by halionaz

> 아 모르겠다 일단 머지 슛~

# Timetable Pages 1차 머지

강의 추가 로직까지 구현하면 PR이 너무 길어질 것 같아 1차적 머지 진행합니다!

## 공통사항
- Pretendard 웹 폰트를 전역 설정했습니다
- 정우님이 자주 쓰시는 shadow 폼이 있길래 그냥 recipe화해서 저장했슴니다 얘는 ui component 구현체가 따로 있는건 아니고 그냥 pandaCSS Recipe라 `cx(shadow())` 형식으로 끌어다 쓰면 되는 것입니다
- 지원누나가 쿠키 정식 명칭을 KU-key로 통일하자 해서 title태그나 Header, Footer 등 수정했습니다

## API 관련
- Friend 기능, Timetable 기능에 필요한 api 로직들을 모두 작성했는데, tanstackQuery랑 axios 모두 처음이라 한번 봐주시면 감사하겠습니다
- src/api/types에 저장된 타입들은 모두 Swagger에 명시되어있는 Request, Response 형식들입니다. 실제 구현할 때 필요하거나, 재사용성이 있어서 정의가 필요한 타입들은 src/types에 저장했어요

## 컴포넌트 구현
- 학기 선택 드롭다운을 구현했습니다
- 시간표 쪽 더미데이터들을 걷어내고, 실제 api로 바꾸었습니다
- 기존에 월~금으로 하드코딩되어있던 시간표를 일정에 맞춰 일요일까지 늘어날 수 있도록 바꾸었습니다
- Modal을 통해 시간표의 색상을 변경, 이름을 수정, 삭제를 할 수 있도록 구현해두었습니다 (관련 컴포넌트들 우선 한 tsx파일 내에 몰아 작성해뒀습니다)
- 친구 수락 / 요청 / 목록 확인 페이지를 구현했습니다
- 로딩 시에 페이지 사이즈가 너무 확확 변해서 스켈레톤 UI (실제 스켈레톤 컴포넌트를 만든건 아니고 initailData를 설정했슴다) 적용했습니다

내용이 좀 많으니... 천천히 여유롭게 검토해주세용
피드백과 수정요청은 언제든 환영입니다 🙌

2024-07-03 15:14 UTC, Virtuso1225 commented on src/api/hooks/auth.ts
> +    keepingLogin: true,
이 부분은 true를 고정값으로 하기로 했나요?

2024-07-03 15:24 UTC, halionaz commented on src/api/hooks/auth.ts
> +    keepingLogin: true,
아 이거 개발할 때 편하려고 넣어둔건데 안빼고 커밋했네 🤦‍♂️

일단 당분간은 더미값 설정해놔야되니 두고, 로그인창 구현할 때 가변값으로 바꾸면 될 것 같슴다

2024-07-04 12:20 UTC, Virtuso1225 requested changes
열심히 리뷰 남겨 봤습니다~!

2024-07-04 12:20 UTC, Virtuso1225 commented on src/api/hooks/friends.ts
> +const getFriendList = async ({ authHeader, keyword }: GetFriendListRequest): Promise<GetFriendListResponse> => {
return 되는 인자값에 대한 타입 추론이 자동으로 될거라 매번 이렇게 안 해도 괜찮을 듯 합니다!
(자동으로 타입 추론 되는 것 한정)

2024-07-04 12:20 UTC, Virtuso1225 commented on src/api/hooks/friends.ts
> +export const useGetFriendList = (props: Omit<GetFriendListRequest, 'authHeader'>) => {
이거 useQuery 문 사용하는 함수와, 내부에서 사용하는 함수 선언을 위 아래로 해두는 건 어떨까요? 내부 함수와 멀리 떨어져 있으니까 위 아래로 움직이는 게 다소 귀찮아보여서.. 다소 사소한 그런 의견 이었습니다

2024-07-04 12:20 UTC, Virtuso1225 commented on src/api/hooks/friends.ts
> +      console.log('친구 요청 보내기 성공')
성공과 에러 처리를 어떻게 로그 찍을지 논의를 해봐야겠네요

2024-07-04 12:20 UTC, Virtuso1225 commented on src/api/hooks/friends.ts
> +export const useGetSearchUser = ({ username }: Omit<GetSearchUserRequest, 'authHeader'>) => {
이것도 사소한 부분인데 개인적으로 
Interface에서 하나만 필요한 경우에는 Omit보다 Pick이 좋을 것 같습니다.
하나의 인자만 필요한데, Omit으로 해두니까 다른 요소도 받아와야하나? 싶어지는, 그래서 타입을 한 번 더 확인하게 되는군요

2024-07-04 12:20 UTC, Virtuso1225 commented on src/api/hooks/timetable.ts
> +export const useGetTimetable = (props: Omit<GetTimeTableByTimeTableIdRequest, 'authHeader'>) => {
이부분도 Pick로 하는 건 어떤가요?

2024-07-04 12:20 UTC, Virtuso1225 commented on src/api/hooks/timetable.ts
> +export const usePostTimetable = () => {
지금 보니까 최대 3개에 달성한 이후에 post했을 때, 에러로 보내고 있는데, 이거 핸들링을 해줘야 유저도 아 최대 3개까지구나!를 알 수 있을 것 같습니당.

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/FriendTimetable/FriendCard.tsx
> +  const isRequest = data.friendshipId !== undefined
이거 약간 request를 보낸 인자로 해석될 여지도 있으니, recievedRequest 같은 걸로 변경하는 거 어떤가요?

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/FriendTimetable/FriendCard.tsx
> +          <div className={css({ fontWeight: 400, fontSize: 12, color: 'darkGray.2' })}>
Major, lang 둘 다 없는 값일 수 있나요?

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/FriendTimetable/FriendRequest.tsx
> +  const { data: requestData } = useGetReceivedList()
```ts
  const { data } = useGetReceivedList()
  const requestData = data ?? []
  ```
  이렇게 선으로 초기화 해주고 밑에 requestData && 없애주는 게 좀 더 안전(?) 깔끔할 것 같아요 개인적으로.?

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/FriendTimetable/FriendsList.tsx
> +  const { data } = useGetFriendList({ keyword: null })
이것도 배열을 초기화 해주는 건 어떤가요

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/FriendTimetable/FriendsList.tsx
> +        {data && data.length > 0 ? (
```ts
  const { data } = useGetFriendList({ keyword: null })
  const friendList = data ?? []
```
  
```ts
        {friendList.length > 0 ? (
          friendList.map(friend => (
            <Link key={friend.userId} className={css(FriendBlock)} to={`/timetable/friend/${friend.username}`}>
              <span>{friend.username}</span>
            </Link>
          ))
        ) : (
          <div className={css(FriendBlock, { cursor: 'default' })}>Hi there~!</div>
        )}
        
```
이런식으로 가능하겠네요

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/FriendTimetable/FriendsManage.tsx
> +  const { data: searchResultData, error } = useGetSearchUser({ username: searchKeyword })
아 이거 Input 입력할때마다 자꾸 query 호출 돼서 이렇게 이중으로 했군요..흠 어떻게 개선할 방법 없으려나

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/FriendTimetable/SearchResult.tsx
> +  error: Error | null
이거 모든 Error에 다 해당하나요? 아니면 AxiosError에만 반응해야하는 건가요? 만일 AxiosError라면 한 번 type narrowing을 해도 좋을 것 같기도. 아니면 뭔가 에러 중에서도 해당 메세지가 no result 인 경우에 no search result만 보여주는 게 좋을듯 합니다.
다른 뭐 서버 에러, 이런 경우하고는 다른 에러이니

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/MyTimetable/ColorSelector.tsx
> +  setGlobalModalState: React.Dispatch<React.SetStateAction<'color' | 'name' | 'delete' | null>>
setState을 그 자체로 넘겨주는 게 지양되는 걸로 알고 있는데, 부모 컴포넌트에서 useCallback으로 감싸서 내려주는 건 어떤가요. 보니까 여러곳에서 setState이 props로 내려지고 있던데, depth가 2단계 인 것도 본 것 같아서, 함수를 만들어서 내려주는 게 좀 더 state를 안전하게 다루지 않을까 싶습니다...!

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/index.tsx
> +          <button className={optBtn()} onClick={() => setIsModalOpen(true)}>
지금 이 부분 확인 해보니까 누를 때마다 테이블 전체가 리렌더링 되고 있는데, 괜찮을까요?

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/MyTimetable/OptionModal.tsx
> +  setGlobalModalState: React.Dispatch<React.SetStateAction<'color' | 'name' | 'delete' | null>>
```ts
  const handleModalState = useCallback(
    (value: 'color' | 'name' | 'delete' | null) => {
      setIsModalOpen(false)
      setGlobalModalState(value)
    },
    [setIsModalOpen, setGlobalModalState],
  )
  ```
  이런 거 만들어서 받으면 좋을 듯 합니다!

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/MyTimetable/SelectTimetableBtn.tsx
> +  curInd: number
밑에는 setCurIndex라고 되어있는데, 다른 코드에서도 ind라고 되어있는 부분을 더러 봤는데, index,혹은 Index라고 해도 큰 문제 없지 않을까요? 오히려 currIndex 같이 작성하는 게 한 눈에 확 들어올듯 합니당

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/MyTimetable/StatusBar.tsx
> +        if (hasTable) {
```ts
        hasTable &&
          !curTimetable.mainTimeTable &&
          (setCurIndex(0),
          updateMainTable({
            semester: curTimetable.semester,
            year: curTimetable.year,
            timeTableId: curTimetable.timeTableId,
          }))
``` 
또는

```ts
        if (hasTable && !curTimetable.mainTimeTable) {
          setCurIndex(0),
          updateMainTable({
            semester: curTimetable.semester,
            year: curTimetable.year,
            timeTableId: curTimetable.timeTableId,
          })
        }
```        
이거는 이렇게 줄일 수 있을 것 같아요

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/MyTimetable/TimetableModal.tsx
> +  const { mutate: changeTableName } = useUpdateTableName()
```ts
  const searchEl = useRef<null | HTMLInputElement>(null)

  useEffect(() => {
    if (searchEl.current) {
      searchEl.current.focus()
    }
  }, [])
```
이런식으로 해서 input에 ref 연결해주면 autoFocus 효과를 낼 수 있습니당

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/MyTimetable/TimetableModal.tsx
> +  setGlobalModalState: React.Dispatch<React.SetStateAction<'color' | 'name' | 'delete' | null>>
이거 globalModalState을 별도의 타입으로 만들어서 관리하는 게 좋을 듯 합니당

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/MyTimetable/TimetableModal.tsx
> +              timeTableId={timeTableId}
timetable은 하나의 단어니까 timetableId 라고 해도 괜찮을 듯 합니다

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/MyTimetable/TimetableModal.tsx
> +interface TimetableModalProps {
근데 이거 모달들을 다 분리 안 하고 하나의 모달 파일에 넣은 이유가 있나요?

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/TimetableLayout.tsx
> +  const { time, week } = getWeeknTimeList(data.courses, data.schedules)
이거 확인해보니까 getWeeknTimeList 호출이 두 번 발생해서 time, week가 두 번 가져와지는 현상이 발생하고 있습니다..!!

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/TimetableLayout.tsx
> +  const { time, week } = getWeeknTimeList(data.courses, data.schedules)
```ts
  const { data, isFetched } = useGetTimetable({ timeTableId })

  const [time, setTime] = useState<string[]>([''])
  const [week, setWeek] = useState<string[]>([])

  useEffect(() => {
    if (isFetched) {
      const { time, week } = getWeeknTimeList(data.courses, data.schedules)
      setTime(time)
      setWeek(week)
    }
  }, [data.courses, data.schedules, isFetched])
```
이렇게 해서 한 번만 호출하게 하는 방향으로 가야할 것 같네요!!

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/index.tsx
> +  const [globalModalState, setGlobalModalState] = useState<null | 'name' | 'color' | 'delete'>(null)
modalState type 만들어 둔 거 있는 거 같던데, 그거 사용하는 거 어떤가요

2024-07-04 12:20 UTC, Virtuso1225 commented on src/components/timetable/index.tsx
> +              if (event.target === event.currentTarget) {
이거는 클릭한 영역이 모달 외부로 일치하는 경우에 null로 바꾸는 거 맞죠?

2024-07-04 12:20 UTC, Virtuso1225 commented on src/pages/TimetablePage/MyTimetablePage.tsx
> +  const semesterList = timetablePreprocess(timetableList)
여기도 마찬가지로 두 번 불리고 있네요

2024-07-04 12:45 UTC, halionaz commented on src/api/hooks/friends.ts
> +const getFriendList = async ({ authHeader, keyword }: GetFriendListRequest): Promise<GetFriendListResponse> => {
이 친구 axios 제너릭 설정이 안 되어있었네요

```ts
const getFriendList = async ({ authHeader, keyword }: GetFriendListRequest) => {
  const response = await axios.get<GetFriendListResponse>(`http://${import.meta.env.VITE_API_SERVER}/friendship`, {
    headers: { Authorization: authHeader },
    params: { keyword },
  })
  return response.data
}
```

요런식으로 바꾸면 더 나을까요?

2024-07-04 12:57 UTC, halionaz commented on src/api/hooks/friends.ts
> +      console.log('친구 요청 보내기 성공')
연승씨와 논의 결과 친구검색 response에
`"status": "me" | "friend" | "requested" | "unknown"` 값을 받아서

- 본인 자신을 검색했을 때 추가적인 request가 불가능한 블럭 제공
- 이미 친구인 사람을 검색했을 때 추가적인 request를 막음
- 이미 친구 요청을 보낸 사람이 왔을 때, 상대의 친구 수락 상태를 확인할 수 있고, 추가적인 request를 막아둠
- 위 세 조건이 모두 아니라면 status에 "unknown"이 와서 기존처럼 정상적으로 친구 요청을 보내는 것이 가능

식으로 구현할 예정입니다 😁

이러면 가시적으로 친구 요청 request가 성공했는지 알 수 있어서 성공 처리는 가능할 것 같은데
에러 처리는 좀 더 생각해봐야겠네요

2024-07-04 13:06 UTC, halionaz commented on src/api/hooks/timetable.ts
> +export const usePostTimetable = () => {
좋은 생각 👍
+ 버튼 비활성화 버전 만들어서 테이블 3개면 버튼 잠가버리는 것도 괜찮은 것 같습니다

2024-07-04 13:36 UTC, Virtuso1225 commented on src/api/hooks/friends.ts
> +const getFriendList = async ({ authHeader, keyword }: GetFriendListRequest): Promise<GetFriendListResponse> => {
좋은 것 같습니당

2024-07-04 14:18 UTC, halionaz commented on src/api/hooks/friends.ts
> +export const useGetSearchUser = ({ username }: Omit<GetSearchUserRequest, 'authHeader'>) => {
이 부분은 Request API 명세가 혹여나 변경되었을 때 코드 변경사항을 최소화하기위해 Omit으로 통일해두었는데요,
(Request에 들어가는 인자가 추가되었을 시, 
Omit을 사용하면 Request Interface만 변경해도 타이핑이 되지만, Pick을 사용하면 Pick 인자도 추가해야 함)
그렇게 하다보니 코드가 상당히 비직관적으로 보이는 것 같습니다

지금 Omit 쓰고 있는 친구들 중에 인자 변경이 없을 것 같아 보이는 엔드포인트들이 몇개 보여서 
이런 애들은 깡 type으로 수정할게요!

2024-07-04 14:32 UTC, Virtuso1225 commented on src/api/hooks/friends.ts
> +export const useGetSearchUser = ({ username }: Omit<GetSearchUserRequest, 'authHeader'>) => {
아 그런 뒷 배경이 있는지 몰랐네여. 굿굿 입니다

2024-07-04 14:34 UTC, Virtuso1225 commented on src/api/hooks/timetable.ts
> +export const usePostTimetable = () => {
비활성화도  좋네요! 근데 약간 알럿 창 처럼 최대 3개까지 가능합니다! 를 보여주는 것도 중요하지 않을까 싶습니다

2024-07-04 14:38 UTC, halionaz commented on src/api/hooks/timetable.ts
> +export const usePostTimetable = () => {
오 맞네요 이부분도 회의때 얘기해봐야겠따

2024-07-04 15:55 UTC, halionaz commented on src/components/timetable/FriendTimetable/FriendRequest.tsx
> +  const { data: requestData } = useGetReceivedList()
너무 좋은 제안입니다! 

이 친구랑 아래쪽 useGetFriendList처럼 
GET 요청으로 받아온 데이터 undefined 여부 체크가 필요한 api들은 모두
```ts
export const useGetReceivedList = () => {
  const authHeader = useAuthHeader()
  return useQuery({
    queryKey: ['friendsRequest'],
    queryFn: () => getReceivedList({ authHeader }),
    initialData: [],
  })
}
```

이런 식으로 query 데이터가 오기 전에 initialData로 빈배열 들어가도록 고칠게요~

2024-07-04 15:57 UTC, halionaz commented on src/components/timetable/FriendTimetable/FriendCard.tsx
> +          <div className={css({ fontWeight: 400, fontSize: 12, color: 'darkGray.2' })}>
지금 테스트 user 데이터들은 모두 major와 lang값이 없어서 일단 이렇게 처리해뒀습니다
그리고 IA 상에서도 회원가입 때 이 두값을 따로 받는거 같지 않고, 마이페이지에 추후 등록하는 user flow로 되어 있어서
이런식으로 구현해뒀어요

근데 얘는 생각해보니 회원가입 때 유저가 입력할 수 있도록 안내하는게 뭔가 더 적절해보여서
회의 때 논의해보는 게 좋을 것 같습니다!
만약 회원가입 시에 입력하는 데이터로 바뀌게 되면 조건부는 생략해도 될 듯 해요

2024-07-04 16:01 UTC, halionaz commented on src/components/timetable/FriendTimetable/FriendsManage.tsx
> +  const { data: searchResultData, error } = useGetSearchUser({ username: searchKeyword })
역시 바로 알아봐주시는군요 회장님 👍

useQuery 이용해서 검색 구현하는 블로그 레퍼런스들과 인류지성의 결정체 ChatGPT께서
이런 형태의 구현을 제안하시더라고요
당장은 더 나은 방법이 안 떠올라서 이렇게 해놨는데 제가 생각해봤을 때도 더 좋은 로직이 있을 것 같습니다

이건 좀 더 고민하고 나중에 리펙토링할게연

2024-07-05 02:13 UTC, halionaz commented on src/components/timetable/MyTimetable/TimetableModal.tsx
> +              timeTableId={timeTableId}
지금 백엔드 API 들어갈때 param으로 timeTableId를 받고 있어서 대소문자 구분이 살짝 제각각인데
시흔씌께 요청해서 timeTable 워딩을 timetable로 통일해보도록 하겠습니다!-!

2024-07-05 02:31 UTC, halionaz commented on src/components/timetable/MyTimetable/TimetableModal.tsx
> +interface TimetableModalProps {
컨텍스트와 기능이 유사하기도 하고, 
시간표 조작 모달의 서브 하위 모달로 여겨지는 것 같은데 컴포넌트 하나하나의 볼륨이 크지 않아서 파일에 꾸겨넣었습니다

오히려 컴포넌트 내에 하위 폴더로 넣으면 더 복잡해 보일 거 같아서 이렇게 했는데 파일을 분리하는게 좋을까요?
"반드시 한 파일에 넣어야겠다"는 의도가 있는건 아니었어서 저희끼리 일관성을 가지는 쪽으로 결정하는 게 좋은 것 같습니다!

2024-07-05 02:33 UTC, halionaz commented on src/components/timetable/index.tsx
> +              if (event.target === event.currentTarget) {
넵 맞습니다~😁

2024-07-05 02:53 UTC, halionaz commented on src/components/timetable/FriendTimetable/SearchResult.tsx
> +  error: Error | null
AxiosError Typing하기 생각보다 좀 까다롭군요

해당 메세지가 no result임이 `error?.response?.data?.message` 이 안쪽에 담겨있는데,
AxiosError로 narrowing 하더라도, data 속 message 객체까지 타이핑하려면 에러 객체를 정형화해야할 것 같습니다

이 부분은 백엔드 연승씌와 조금 더 협의를 본 후에 고치도록 할게요!!

2024-07-05 03:12 UTC, halionaz commented on src/components/timetable/MyTimetable/ColorSelector.tsx
> +  setGlobalModalState: React.Dispatch<React.SetStateAction<'color' | 'name' | 'delete' | null>>
오 그런가요??? 처음 안 사실이네요
약간 Reducer 사용하듯 활용하는게 권장되는군요

setState prop으로 넘기는 부분들은 피드백 적용해서 수정해두도록 하겠습니다!

2024-07-05 04:41 UTC, halionaz commented on src/components/timetable/index.tsx
> +          <button className={optBtn()} onClick={() => setIsModalOpen(true)}>
`TimetableLayout` 컴포넌트 memo() 처리해서 최적화하도록 하겠습니다 !

2024-07-05 04:49 UTC, halionaz commented on src/components/timetable/MyTimetable/TimetableModal.tsx
> +  const { mutate: changeTableName } = useUpdateTableName()
autoFocus 사용하는 것이 간결할 거 같아서 이렇게 구현해두었는데
ref와 useEffect를 사용해 작성하는 게 더 나을까요?

2024-07-05 05:20 UTC, halionaz commented on src/components/timetable/TimetableLayout.tsx
> +  const { time, week } = getWeeknTimeList(data.courses, data.schedules)
요런 성능 이슈는 개발할 때 생각을 별로 안해봤었는데 진짜 너무 영양가 높은 리뷰네요 😁👍
우선, 이 친구는 의도한 두 번 호출입니다!

timeTable data가 로딩 되기 전에도 스켈레톤 시간표가 떴으면해서, 
우선 빈 배열 data로 time과 week가 계산되어서 시간표가 표시됩니다.

이후에, data가 불러와지면 시간표에 들어있는 강의 데이터를 기반으로 다시 time과 week가 계산되는데요,
만일 강의 시간이 default 시간표의 최댓값인 오후 5시를 넘어가거나, 토/일 일정이 끼어있는 경우 시간표가 확장됩니다.

TimetableLayout은 tableId만을 인자로 받아 시간표를 띄워주는 컴포넌트라 state나 prop으로 인한 리렌더링이 발생할 거 같진 않고,
React.memo를 통해 리렌더링도 막아놔서 성능 상 이슈 일으키지 않도록 최적화해두었습니다!!
꼼꼼한 피드백 감사드려요~~~

2024-07-05 05:26 UTC, halionaz commented on src/pages/TimetablePage/MyTimetablePage.tsx
> +  const semesterList = timetablePreprocess(timetableList)
이 친구도 마찬가지로 timetableList의 initialData가 빈배열로 설정되어 있어 데이터 패칭 전에 빈 page를 구성하게 해두고,
이후에 fetch가 끝나면 실제 시간표 데이터가 임베딩되도록 짜둬서 실제 성능적 이슈는 없을 것 같습니다!

2024-07-05 06:05 UTC, Virtuso1225 commented on src/components/timetable/MyTimetable/TimetableModal.tsx
> +interface TimetableModalProps {
다시 보니까 크게 상관 없을 것 같기도 하네용

2024-07-05 06:08 UTC, Virtuso1225 commented on src/components/timetable/TimetableLayout.tsx
> +  const { time, week } = getWeeknTimeList(data.courses, data.schedules)
`getWeeknTimeList ` 자체가 크게 무거운 함수는 아닌 거 같아서 두 번 호출되어도 문제가 없어보이긴 하는데, 만일 스켈레톤 시간표가 뜨는 걸 의도하신 거라면, 함수의 호출을 한 번으로 제한하고, react-query에서 제공하는 isPending, 같은 state을 통해서 isPending인 경우에 skeleton ui를 return 하는 것도 하나의 옵션일 수 있겠네요.

2024-07-05 06:16 UTC, Virtuso1225 commented on src/components/timetable/MyTimetable/TimetableModal.tsx
> +  const { mutate: changeTableName } = useUpdateTableName()
아 만일 eslint 주석처리 하는 게 좀 거슬린다 하면 이렇게 해도 될 것 같은데, 큰 이슈가 아니라면 그냥 autofocus 써도 될듯 합니다.

2024-07-05 06:16 UTC, Virtuso1225 commented on src/components/timetable/TimetableLayout.tsx
> +  const { time, week } = getWeeknTimeList(data.courses, data.schedules)
그리고 지금 빈 배열로 전달 될 때 보여지는 skeleton 이 어떤 건지 알 수 있을까요?

2024-07-05 06:35 UTC, halionaz commented on src/components/timetable/TimetableLayout.tsx
> +  const { time, week } = getWeeknTimeList(data.courses, data.schedules)
원래 말씀하신거처럼 isPending 상태에서 보여지는 skeleton UI를 따로 만들어서 띄우려고 했는데
skeleton을 만들다 보니 그냥 data만 빈 배열로 바꾼 똑같은 ui를 만들고 있더라고요.
그래서 react query에서 제공하는 initialData를 이용해서 pending 중에는 
useQuery가 빈 배열을 뱉도록 해서 강의가 없는 빈 시간표가 띄워지도록 구현해뒀습니다.

참고로 빈배열이 `getWeeknTimeList`에 들어가면 현재는 단순히 
```ts
{
    time : ['09:00','10:00',.... , '16:00'],
    week : ['MON', 'TUS', 'WEN', 'THR', 'FRI', 'SAT', 'SUN']
}
```
가 나오게 되어 있어서 부하는 없습니다

만일 skeleton을 따로 디자인할 필요가 있다면 (단순 빈 시간표와 디자인이 달라야 할 필요가 있다면)
현재처럼 initData를 받아와 렌더링하고, 실제 데이터가 도착하면 다시 렌더링하는 식에서
skeleton 컴포넌트를 isPending으로 선택적으로 보이게 구현하게 바꾸려고 합니다

요거는 나중에 대면 회의때 실제 로직 보여드리고 싶은데 가능할까용

2024-07-05 08:59 UTC, Virtuso1225 commented on src/components/timetable/TimetableLayout.tsx
> +  const { time, week } = getWeeknTimeList(data.courses, data.schedules)
좋습니다~

2024-07-05 08:59 UTC, Virtuso1225 approved these changes

2024-07-05 10:12 UTC, merged